[tox]
isolated_build = True
envlist = py311-light, py311-all, py312-light, py312-all

[testenv]
skip_install = true
allowlist_externals = uv
passenv = *
commands =
    uv run --no-sync pytest {posargs}

# Run: tox -e py311-light -- tests/unit
[testenv:py311-light]
basepython = python3.11
commands_pre =
    uv sync --python 3.11

# Run: tox -e py311-all -- tests/unit
[testenv:py311-all]
basepython = python3.11
commands_pre =
    uv sync --python 3.11 --extra all

# Run: tox -e py312-light -- tests/unit
[testenv:py312-light]
basepython = python3.12
commands_pre =
    uv sync --python 3.12

# Run: tox -e py312-all -- tests/unit
[testenv:py312-all]
basepython = python3.12
commands_pre =
    uv sync --python 3.12 --extra all